- name: nginx installation and run
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: run
     enabled: yes

       