- name: devops engineer details
  hosts: local
  connection: local
  vars_files:
   - course.yml 
  tasks:
  - name: printing roles
    ansible.builtin.debug:
     msg: "role {{role}}, hours {{hours}}, work {{work}}}"