- name: devops engineer details
  hosts: local
  connection: local
  vars:
   role: Devops engineer
   hours: 3hrs
   work: Operations
  tasks:
  - name: printing roles
    ansible.builtin.debug:
    msg: "role {{role}}, hours {{hours}}, work {{operations}}"