- name: prompting variables #hide username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: enter the username
    private: false

  - name: PASSWORD
    prompt: enter the PASSWORD
    private: false
  tasks:
  - name: printing username and password hiding
    ansible.builtin.debug:
     msg: "username {{USERNAME}}, password {{PASSWORD}}"  
   