- name: install softwares
  hosts: frontend
  become: yes
  tasks:
  - name: software installtion
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip
