- name: install softwares
  hosts: local
  connection: local
  tasks:
  - name: software installtion
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip
