- name: install softwares
  hosts: frontend
  become: yes
  tasks:
  - name: software installtion
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present' }
    - { name: 'mysql', state: 'absent' }